INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(),'TRABALHO');

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(),'FAMÍLIA');

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(),'ESTUDO');

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(),'LAZER');

INSERT INTO CATEGORIA(ID, NOME)
VALUES(NEWID(),'OUTROS');

SELECT * FROM CATEGORIA;